name: Mkdocs
on:
  # each day at 0200 hours
  schedule:
    - cron: "0 0 * * *"
  # each push
  push:
jobs:
  "doc":
    name: "Build mkdocs"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: "Setup Python 3 on runner"
        uses: actions/setup-python@v2.1.4
        with:
          python-version: "3.x"
      - name: "Build mkdocs content to site folder"
        run: |
          pip install -r .github/requirements.txt
          python .github/index.py
          mkdocs build -f mkdocs.yml
      - name: "Deploy last version to gh-pages"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
